project:
  type: website
  output-dir: docs

website:
  title: "My Personal Website for STAT 37815"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/jliucx/jliucx.github.io

format:
  html:
    theme: Litera
    mainfont: "'Roboto', sans-serif"
